# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mcy-mcy/文档/chatroom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mcy-mcy/文档/chatroom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mcy-mcy/文档/chatroom/CMakeFiles /home/mcy-mcy/文档/chatroom//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mcy-mcy/文档/chatroom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named FTP_serve

# Build rule for target.
FTP_serve: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FTP_serve
.PHONY : FTP_serve

# fast build rule for target.
FTP_serve/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/build
.PHONY : FTP_serve/fast

Database/Database.o: Database/Database.cpp.o
.PHONY : Database/Database.o

# target to build an object file
Database/Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Database/Database.cpp.o
.PHONY : Database/Database.cpp.o

Database/Database.i: Database/Database.cpp.i
.PHONY : Database/Database.i

# target to preprocess a source file
Database/Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Database/Database.cpp.i
.PHONY : Database/Database.cpp.i

Database/Database.s: Database/Database.cpp.s
.PHONY : Database/Database.s

# target to generate assembly for a file
Database/Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/Database/Database.cpp.s
.PHONY : Database/Database.cpp.s

cli/User.o: cli/User.cpp.o
.PHONY : cli/User.o

# target to build an object file
cli/User.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/cli/User.cpp.o
.PHONY : cli/User.cpp.o

cli/User.i: cli/User.cpp.i
.PHONY : cli/User.i

# target to preprocess a source file
cli/User.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/cli/User.cpp.i
.PHONY : cli/User.cpp.i

cli/User.s: cli/User.cpp.s
.PHONY : cli/User.s

# target to generate assembly for a file
cli/User.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/cli/User.cpp.s
.PHONY : cli/User.cpp.s

cli/chat_client.o: cli/chat_client.cpp.o
.PHONY : cli/chat_client.o

# target to build an object file
cli/chat_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/cli/chat_client.cpp.o
.PHONY : cli/chat_client.cpp.o

cli/chat_client.i: cli/chat_client.cpp.i
.PHONY : cli/chat_client.i

# target to preprocess a source file
cli/chat_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/cli/chat_client.cpp.i
.PHONY : cli/chat_client.cpp.i

cli/chat_client.s: cli/chat_client.cpp.s
.PHONY : cli/chat_client.s

# target to generate assembly for a file
cli/chat_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/cli/chat_client.cpp.s
.PHONY : cli/chat_client.cpp.s

cli/menu.o: cli/menu.cpp.o
.PHONY : cli/menu.o

# target to build an object file
cli/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/cli/menu.cpp.o
.PHONY : cli/menu.cpp.o

cli/menu.i: cli/menu.cpp.i
.PHONY : cli/menu.i

# target to preprocess a source file
cli/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/cli/menu.cpp.i
.PHONY : cli/menu.cpp.i

cli/menu.s: cli/menu.cpp.s
.PHONY : cli/menu.s

# target to generate assembly for a file
cli/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/cli/menu.cpp.s
.PHONY : cli/menu.cpp.s

include/Threadpool.o: include/Threadpool.cpp.o
.PHONY : include/Threadpool.o

# target to build an object file
include/Threadpool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/include/Threadpool.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/include/Threadpool.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/include/Threadpool.cpp.o
.PHONY : include/Threadpool.cpp.o

include/Threadpool.i: include/Threadpool.cpp.i
.PHONY : include/Threadpool.i

# target to preprocess a source file
include/Threadpool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/include/Threadpool.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/include/Threadpool.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/include/Threadpool.cpp.i
.PHONY : include/Threadpool.cpp.i

include/Threadpool.s: include/Threadpool.cpp.s
.PHONY : include/Threadpool.s

# target to generate assembly for a file
include/Threadpool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/include/Threadpool.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/include/Threadpool.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/include/Threadpool.cpp.s
.PHONY : include/Threadpool.cpp.s

include/inetsockets_tcp.o: include/inetsockets_tcp.cpp.o
.PHONY : include/inetsockets_tcp.o

# target to build an object file
include/inetsockets_tcp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/include/inetsockets_tcp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/include/inetsockets_tcp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/include/inetsockets_tcp.cpp.o
.PHONY : include/inetsockets_tcp.cpp.o

include/inetsockets_tcp.i: include/inetsockets_tcp.cpp.i
.PHONY : include/inetsockets_tcp.i

# target to preprocess a source file
include/inetsockets_tcp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/include/inetsockets_tcp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/include/inetsockets_tcp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/include/inetsockets_tcp.cpp.i
.PHONY : include/inetsockets_tcp.cpp.i

include/inetsockets_tcp.s: include/inetsockets_tcp.cpp.s
.PHONY : include/inetsockets_tcp.s

# target to generate assembly for a file
include/inetsockets_tcp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/include/inetsockets_tcp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/include/inetsockets_tcp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/include/inetsockets_tcp.cpp.s
.PHONY : include/inetsockets_tcp.cpp.s

ser/FTP_serve.o: ser/FTP_serve.cpp.o
.PHONY : ser/FTP_serve.o

# target to build an object file
ser/FTP_serve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/ser/FTP_serve.cpp.o
.PHONY : ser/FTP_serve.cpp.o

ser/FTP_serve.i: ser/FTP_serve.cpp.i
.PHONY : ser/FTP_serve.i

# target to preprocess a source file
ser/FTP_serve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/ser/FTP_serve.cpp.i
.PHONY : ser/FTP_serve.cpp.i

ser/FTP_serve.s: ser/FTP_serve.cpp.s
.PHONY : ser/FTP_serve.s

# target to generate assembly for a file
ser/FTP_serve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTP_serve.dir/build.make CMakeFiles/FTP_serve.dir/ser/FTP_serve.cpp.s
.PHONY : ser/FTP_serve.cpp.s

ser/chat_serve.o: ser/chat_serve.cpp.o
.PHONY : ser/chat_serve.o

# target to build an object file
ser/chat_serve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/ser/chat_serve.cpp.o
.PHONY : ser/chat_serve.cpp.o

ser/chat_serve.i: ser/chat_serve.cpp.i
.PHONY : ser/chat_serve.i

# target to preprocess a source file
ser/chat_serve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/ser/chat_serve.cpp.i
.PHONY : ser/chat_serve.cpp.i

ser/chat_serve.s: ser/chat_serve.cpp.s
.PHONY : ser/chat_serve.s

# target to generate assembly for a file
ser/chat_serve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/ser/chat_serve.cpp.s
.PHONY : ser/chat_serve.cpp.s

ser/serve.o: ser/serve.cpp.o
.PHONY : ser/serve.o

# target to build an object file
ser/serve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/ser/serve.cpp.o
.PHONY : ser/serve.cpp.o

ser/serve.i: ser/serve.cpp.i
.PHONY : ser/serve.i

# target to preprocess a source file
ser/serve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/ser/serve.cpp.i
.PHONY : ser/serve.cpp.i

ser/serve.s: ser/serve.cpp.s
.PHONY : ser/serve.s

# target to generate assembly for a file
ser/serve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/ser/serve.cpp.s
.PHONY : ser/serve.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FTP_serve"
	@echo "... client"
	@echo "... server"
	@echo "... Database/Database.o"
	@echo "... Database/Database.i"
	@echo "... Database/Database.s"
	@echo "... cli/User.o"
	@echo "... cli/User.i"
	@echo "... cli/User.s"
	@echo "... cli/chat_client.o"
	@echo "... cli/chat_client.i"
	@echo "... cli/chat_client.s"
	@echo "... cli/menu.o"
	@echo "... cli/menu.i"
	@echo "... cli/menu.s"
	@echo "... include/Threadpool.o"
	@echo "... include/Threadpool.i"
	@echo "... include/Threadpool.s"
	@echo "... include/inetsockets_tcp.o"
	@echo "... include/inetsockets_tcp.i"
	@echo "... include/inetsockets_tcp.s"
	@echo "... ser/FTP_serve.o"
	@echo "... ser/FTP_serve.i"
	@echo "... ser/FTP_serve.s"
	@echo "... ser/chat_serve.o"
	@echo "... ser/chat_serve.i"
	@echo "... ser/chat_serve.s"
	@echo "... ser/serve.o"
	@echo "... ser/serve.i"
	@echo "... ser/serve.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

