#define SERVE_PORT 8080
#define MSGBUF 64
#define LOGIN 1
#define EXIT 2
#define SIGNIN 3
#define BREAK 4
#define FORGET_PASSWORD 5
#define CHECK_ANS 6
#define IN_ONLINE 7
#define LOGOUT 8
#define ADD_FRIEND 9
#define ASK_ADD_FRIEND 10
#define GET_OFFLINE_MSG 11
#define REFLACT 1000
#define MESSAGE 2000
#define ERROR 3000
#define EPSIZE 1024
#define REACTSIZE 48
#define HANDLE_RECV_NUM 96
